---
title: "1"
---

## Question
Let $x$ be a nilpotent element of a ring $A$. Show that $1+x$ is a unit of $A$. Deduce that the sum of a nilpotent element and an unit is a unit.

## Solution
Fact: If $x$ is a nilpotent element of a ring, then the infinite sum $\displaystyle y =\sum_{n=0}^\infty x^n$ is well defined as an element of the ring $A$. This element is a unit of $A$ and $\displaystyle (1-x)(\sum_{n=0}^\infty x^n) = 1$. 

Proof: Let $x^{N+1}=0$. Then $\displaystyle \sum_{n=0}^\infty x^n = 1+\cdots+x^N$.  
So $\displaystyle (1-x)(\sum_{n=0}^\infty x^n) = (1-x)(1+\cdots+x^N) = (1+\cdots+x^N)-(x+\cdots+x^{N+1}) = 1 - x^{N+1} = 1.$  

If $x$ is nilpotent, then $-x$ is also nilpotent. In particular if $x^N=0$, then $(-x)^N=0$. So the above proof implies: $$\big(1-(-x)\big)\big(\sum_{n=0}^\infty (-x)^n\big) = 1.$$  
Hence $(1+x)\big(1-x+x^2-\cdots+(-1)^Nx^N\big)=1$.

Let us now consider the generalisation. Suppose $u$ is an unit of $A$ and $n$ is a nilpotent element of $A$. Let $s = u + n$. Now to use the result we just proved we have to some way relate it to a sum of the form $1+x$. There are two facts:  
(a). The product of a nilpotent element with any other element is also nilpotent.  
(b). If $v$ is an unit, then an element $a$ of the ring is an unit if and only if the element $va$ is also an unit.  
So to prove that $u+n$ is a unit it is sufficient to prove $v(u+n)$ is also an unit for some unit $v$. We want the product $v(u+n)$ to be of the form $1+x$, where $x$ is nilpotent. The most suggestive candidate for $v$ is $u^{-1}$. But $u^{-1}(u+n)=1+u^{-1}n$. This last sum is of the form $1+x$, with $x$ nilpotent. So this sum is an unit. Hence the original sum is an unit. 

**Almost every exercise in this book teaches us an important fact, that we need to remember. When working in Algebraic geometry all these facts are very useful. In fact that is the purpose of the exercises, particularly in this book.**

The first fact to remember is that the sum and difference of a unit and nilpotent is an unit. So $\pm u \pm n$ is a unit keeping in mind that $-1$ is a unit in any ring.

Fact: the sum of two nilpotents is nilpotent.

Proof: Let $a^{n_1}=0$ and $b^{n_2}=0$. Then $\displaystyle (a+b)^{n_1+n_2-1} = \sum_{i+j=n_1+n_2-1}a^ib^j$. But if $i\leq n_1-1$, then $j = n_1+n_2-1-i=n_2 + (n_1-1-i)\geq n_2$. So in every summand of this binomial sum the power of $a$ is atleast $n_1$ or the power of $b$ is atleast $n_2$. So in all summands either the power of $a$ is $0$ or the power of $b$ is $0$. So every summand is $0$. So the sum $0$. Hence $(a+b)^{n_1+n_2-1}=0$. 

It is instructive verify these facts(that hold in commutative rings ) for square matrices, with entries in commutative rings. If $R$ is a commutative ring, then $M_n(R)$ denotes the ring of $n\times n$ matrices with coefficients in $R$. $M_n(R)$ has a subring $RI_n$ that lies at the center of the matrix ring, and $M_n(R)$ is a $R-$algebra.    
(a). If $A$ is nilpotent, then $I+A$ is a unit. The proof of this is same as that of first part above. This is because the sub-algebra(sub-ring) generated by $A$ over $R$ in $M_n(R)$ is a commutative ring and all computations occur in this commutative ring. This ring is the image of $R[x]$ under the homomorphism $R[x]\to M_n(R),\quad x\mapsto A$.  
(b). If $A$ is nilpotent, and $B$ is another matrix. Then $AB$ maynot be nilpotent. Consider $$A = \begin{pmatrix} 0 & 1 \\ 0 & 0 \end{pmatrix}, \quad B = \begin{pmatrix} 0 & 0 \\ 1 & 0 \end{pmatrix}.$$ Then $A$ is strictly upper-triangular, so it is nilpotent ($A^2 = 0$).$B$ is strictly lower-triangular, so it is also nilpotent ($B^2 = 0$).Now let's compute the product $AB$:$$AB = \begin{pmatrix} 0 & 1 \\ 0 & 0 \end{pmatrix} \begin{pmatrix} 0 & 0 \\ 1 & 0 \end{pmatrix} = \begin{pmatrix} 1 & 0 \\ 0 & 0 \end{pmatrix}.$$ The product is a diagonal matrix with units in the diagonal. Such a matrix cannot be nilpotent. In fact a finite diagonal matrix is nilpotent iff the entries of the diagonal are nilpotent. So product of two nilpotents can be non-nilpotent.  
(c). If $N$ is a nilpotent matrix and $A$ commutes with N, the $AN$ is nilpotent. A pair of commuting matrices generates a commutative sub ring over the base ring. So all computations involving only them is done in that commutative ring. So properties that hold in commutative rings also holds good here.   
(d). It is true that $A$ is a unit iff there exists another unit $B$, such that $AB$ is a unit.  
(e). The sum of unit and nilpotent need not be a unit in matrices. $$N = \begin{pmatrix} 0 & 1 \\ 0 & 0 \end{pmatrix},U = \begin{pmatrix} 1 & 0 \\ 1 & 1 \end{pmatrix}.$$ Then $$U + N =\begin{pmatrix} 1 & 1 \\ 1 & 1 \end{pmatrix}$$ which is not invertible as its determinant is $0$.  
(f). But if $U$ and $N$ commute, then $U^{-1}$ and $N$ also commute . So that $U^{-1}(U+N) = I + U^{-1}N$, But $U^{-1}N$ is nilpotent by what we have said above. So $I + U^{-1}N$ is an unit by what we have said before. So if $U,N$ commute then $U+N$ is an unit. 
