--- 
title: "Exercise 1.1"
---

### Exercise 1.1 (a)

Let $Y$ be the plane curve $y=x^2$ (i.e., $Y$ is the zero set of the polynomial $f=y-x^2$ ). Show that $A(Y)$ is isomorphic to a polynomial ring in one variable over $k$.

### Solution:

Here $f$ is a polynomial in $k[x,y]$. Polynomials in $k[x,y]$ are polynomials in the variables $x$ and $y$. We can evaluate such a polynomial when $x$ has the value $x_0$ and $y$ has the value $y_0$ where $x_0,y_0$ are elements of the field $k$ to get $f(x_0,y_0)$ which is also an element of $k$.  

So given a polynomial in $k[x,y]$, it can be evaluated at a point $p_0=(x_0,y_0)$ in $\mathbb A^2_k$ to get a value in $k$. This process gives a map $$Eval_{p_0}:k[x,y]\to k, \quad g\mapsto g(p_0).$$ This map is often called the *evaluation map* at the point $p_0$. There is an algebraic way to get this map.  

Let $p_0$ denote the point $(x_0,y_0)$ in $\mathbb A^2_k$. Consider the ideal $\mathfrak m_{p_0} = (x-x_0,y-y_0)$. This is the ideal generated by the linear polynomials $x-x_0$, and $y-y_0$. We have:

The set of all polynomials that vanish at the point $p_0=(p_{x_0},p_{y_0})$ is exactly the ideal $\mathfrak m_{p_0}$. 

Proof: Let $u = x - p_{x_0}$ and $v = y - p_{y_0}$. Then $u$ and $v$ are polynomials in $k[x,y]$. Given a polynomial $g(x,y)$ we can write it as polynomial in $u$ and $v$, by writing $g(x,y)=g(u+p_{x_0},v+p_{y_0})$ and expanding the RHS. When the RHS is expanded we get a polynomial $h(u,v)$ in $u,v$. The polynomial $g(x,y)$ and $h(u,v)$ are the same element of the ring $k[x,y]$. $$g \Bigg |_{x=p_{x_0},y=p_{y_0}} = h\Bigg |_{u=0,v=0}.$$ So the constant term of the polynomial $h$ is $g(p_{x_0},p_{y_0})$. Hence we can write $h(u,v)$ as $uh_1(u,v)+vh_2(u,v)+g(p_{x_0},p_{y_0})$ for some polynomials $h_1$ and $h_2$. Since $g(x,y)=h(u,v)$, we have that $g(x,y)=(x-p_{x_0})h_1(u,v) + (y-p_{y_0})h_2(u,v) + g(p_{x_0},p_{y_0})$. So $g(x,y)-g(p_{x_0},p_{y_0})\in \mathfrak m_{p_0}$. 

If $g(p_{x_0},p_{y_0})=0$, then $g(x,y)\in\mathfrak m_{p_0}$. Conversely if $g(x,y)\in\mathfrak m_{p_0}$, then $g(p_{x_0},p_{y_0}) = 0$ as $(p_{x_0},p_{y_0})$ is a common zero of the generators $x-p_{x_0},y-p_{y_0}$ of $\mathfrak m_{p_0}$. 

So $I(\{p_0\}) = \mathfrak m_{p_0}$. 

Fact: If $R$ is a $k-$algebra for a field $k$, and $I$ is a proper ideal of $R$. Then the quotient ring homomorphism $R\to R/I$ gives the structure of a $k-$algebra to $R/I$. In particular the quotient map is identity on $k\subset R$. 

Consider the following map:

$$k[x,y]\to k[x,y]/\mathfrak m_{p_0},\quad f\mapsto \overline{f}$$

As the zero set of $\mathfrak m_{p_0}$ is nonempty, it does not contain any nonzero constant, because a non zero constant has empty zero set. So the above map is a $k-$algebra map and its restriction to $k$ is injective.  Also if $f\in k[x,y]$, then $f-f(p_0)\in\mathfrak m_{p_0}$. So $\overline{f-f(p_0)} = 0$. So $\overline{f} =\overline{f(p_0)}$. So we can say $f\mapsto \overline{f(p_0)}$. As the above map is surjective, we have that the image of $k[x,y]$ is same as the image of $k$ under the above map. Hence the image is exactly $k$. Please note here we are identifying the images of elements of $k\in k[x,y]$ with their images in the quotient. With this identification $\overline f = f(p_0)$. 

So the value of $f$ evaluated at $p_0$ is the image of $f$ under the quotient map $$k[x,y]\to k[x,y]/\mathfrak m_{p_0}.$$.

This is how "Evaluation at $p_0$" can be intrepreted algebraically. 

Fact: Since the quotient of $\mathfrak m_{p_0}$ is a field, the ideal $\mathfrak m_{p_0}$ must be a maximal ideal of a $k[x,y]$.

All these things that we have seen in $2-$variables also holds good for the $n-$variable case.

Facts: 

* If $f_1,\ldots,f_k$ generate an ideal $I$ in $k[x_1,\ldots,x_n]$, then $Z(I)=Z(\{f_1,\ldots,f_k\})$.
* Let $g(x_1,\ldots,x_n)\in k[x_1,\ldots,x_n]$ and $p_0=(p_{1_0},\ldots,p_{n_0})\in\mathbb A^n_k$. Then $g(x_1,\ldots,x_n)-g(p_{1_0},\ldots,p_{n_0})\in\mathfrak m_{p_0}$. and $I(\{(p_{1_0},\ldots,p_{n_0})\})=\mathfrak m_{p_0}$ The proof of this fact is the extension of the proof given above for the $2-$variable case to the $n-$variable case.
* If $p_0\in \mathbb A^n_k$, then $\mathfrak m_{p_0}$ is a maximal ideal of $k[x_1,\ldots,x_n]$. 

**Note: We have not used that $k$ is algebraically closed in the above discussion. Hence all this holds for non algebraically closed fields also.**

$Y:=\{p\in\mathbb A^2_k:f(p)=0\}$. Elements of $k[x,y]$ are seen as functions on $\mathbb A^2_k$. $A(Y)$ is the set of functions we get by restricting the functions on $\mathbb A^2_k$ to $Y$. There is a natural map $$k[x,y]\to A(x,y),\quad f\mapsto f\Bigg|_{Y}.$$ This map is surjective because every element of $A(Y)$ is restriction of an element of $k[x,y]=A(\mathbb A^k)$. Hence this map is a quotient map as this map is also a $k-$algebra map. If $f$ and $g$ are two elements of $k(x,y)$, that restrict to the same function on $Y$, then $f-g$ must be identically zero on $Y$. So $f-g\in I(Y)$. The converse also holds, so the kernel of this map is exactly $I(Y)$. So $A(Y)=k[x,y]/I(Y)$. Note when we are thinking of $A[Y]$ as the quotient ring, there is a concrete realization of it as a ring of functions on $Y$, behind the algebraic object, such that any two polynomials in the equivalence classes given by the quotient map evaluate to the the same value when restricted to $Y$.

When we say $Y$ is the plane curve, we mean $Y$ is the set of point satisfying the equation $y=x^2$. The equation $y=x^2\equiv y-x^2=0$. So a solution of this equation is same as the zero of the polynomial $y-x^2$. So bringing everything to one side of the equation involving polynomials, the solution set becomes the zero set of a polynomials. So studying solutions of polynomial equations is equal to studying zeroes of polynomials. If $I=(f)$, then $Z(I)=Z(\{f\})=Z(f)$.  

So $Z((f))=Y$. $A(Y) = k[x,y]/I(Z((f)))$.

By **Hilbert's Nullstellensatz** $I(Z((f))) = \sqrt {(f)}$. This is an important step.

Fact: The polynomial $y-x^2$ is irreducible.

Proof:Let us briefly recall Eisenstein's criterion. It's simplest form is the following:

Let $f(x)=a_0x^n+a_1x^{n-1}+\cdots+a_n$ be a plynomial in $\mathbb Z[x]$. Suppose there exists a prime number $p\in\mathbb Z$ such that $p\nmid a_0$, $p|a_k$ for $k>0$, and $p^2\nmid a_n$. Then $f(x)$ is irreducible in $\mathbb Z[x]$. 

Proof: 

Fact: For a ring $R$, if $\mathfrak p$ is a prime ideal in $R$, then $\mathfrak pR[x]$ is a prime ideal in $R[x]$.

Proof: Consider the ring extension $R\subset R[x]$. Then $\mathfrak p^e$ the extension of $\mathfrak p$ in $R[x]$ is $\mathfrak pR[x]$. The set of all polynomials in $R[x]$ whose coefficients belong to $\mathfrak p$ is denoted $\mathfrak p[x]$. This is an ideal. We also have that $\mathfrak pR[x]=\mathfrak p[x]$. This fact essentially gives us the description of $\mathfrak p^e$ as all those polynomials whose coeeficients are in $\mathfrak p$. This is also true for a general ideal $I$ of $R$. $I^e=I[x]$, where $I[x]$ is described analogously. **Note: In a general extension $R\subset S$, the extension ideals maynot have a such a simple descris iption.** Consider the s.e.s (short exact sequence) $$0\to I\to R\to \frac{R}{I}\to 0.$$ This is a s.e.s of $R-$modules. 

For every ring $R$, there is a canonical $\mathbb Z$ algebra structure on $R$ given by the **the** "cannonical" map $$\mathbb Z\to R, \quad n\mapsto n\cdot 1_R.$$ Using this every $R-$module is canonically a $\mathbb Z$ module and every $R-$module map is a $\mathbb Z-$module map. Hence the above s.e.s is also a sequence of $\mathbb Z$ modules and $\mathbb Z-$module morphisms. The kernels and the images are the same wether we consider it as $R-$module sequence or a $\mathbb Z-$module sequence. So the exactness of the sequence which depends upon certain equality of these sets also does not change. Hence the above sequence is also exact as a sequence of $\mathbb Z-$modules. So the above sequence is a s.e.s of $\mathbb Z$ modules also. 

We Using this the above sequence is (canonically) a s.e.s of $\mathbb Z$ modules. As a $\mathbb Z$ module the ring $\mathbb Z[x]$ is a direct sum $\bigoplus_{n=0}^\infty \mathbb Zx^n$ of the flat $\mathbb Z$ modules $\mathbb Zx^n$. A direct sum of flat modules is a flat module. So the ring $\mathbb Z[x]$ is a flat $\mathbb Z$ module.   
This is a s.e.s of $\mathbb Z$ modules
by the Eisenstein's criterion applied to the ring $k[y][x]$, which is the polynomial ring in $x$ with coefficients in the ring 





